### 02 Build dim_product

#### This notebook creates the product dimension table from the cleaned sales dataset.

#### Each row in `dim_product` represents one unique product.

In [1]:
import pandas as pd
import os

In [2]:
input_path = "../data/processed/clean_sales.csv"
output_path = "../data/processed/dim_product.csv"

In [3]:
df = pd.read_csv(input_path)
df.head()

,ï»¿row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,order_year,order_month,order_day,order_month_name,order_day_name,date_id
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,11,8,November,Tuesday,2016-11-08
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,11,8,November,Tuesday,2016-11-08
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,6,12,June,Sunday,2016-06-12
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,10,11,October,Sunday,2015-10-11
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,10,11,October,Sunday,2015-10-11

In [4]:
df[["product_id", "product_name", "category", "sub_category"]].head()

,product_id,product_name,category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

In [5]:
dim_product = df[["product_id", "product_name", "category", "sub_category"]].copy()

In [8]:
dim_product = dim_product.drop_duplicates()

In [7]:
print("dim_product shape:", dim_product.shape)
dim_product.head()

dim_product shape: (9994, 4)

,product_id,product_name,category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

In [9]:
dim_product.isna().sum()

product_id      0
product_name    0
category        0
sub_category    0
dtype: int64

In [10]:
text_cols = ["product_name", "category", "sub_category"]

for col in text_cols:
    dim_product[col] = dim_product[col].astype(str).str.strip()

In [11]:
dim_product = dim_product.sort_values(by=["category", "sub_category", "product_name"]).reset_index(drop=True)

In [12]:
dim_product = dim_product.sort_values(by=["category", "sub_category", "product_name"]).reset_index(drop=True)

In [13]:
print("Rows:", len(dim_product))
print("Unique product_id:", dim_product["product_id"].nunique())
print("Unique product_name:", dim_product["product_name"].nunique())

Rows: 1894
Unique product_id: 1862
Unique product_name: 1850

In [14]:
os.makedirs("../data/processed", exist_ok=True)
dim_product.to_csv(output_path, index=False)
print(f"dim_product saved to: {output_path}")

dim_product saved to: ../data/processed/dim_product.csv

In [16]:
dim_product.head(10)

,product_id,product_name,category,sub_category
0,FUR-BO-10002202,"Atlantic Metals Mobile 2-Shelf Bookcases, Cust...",Furniture,Bookcases
1,FUR-BO-10002545,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",Furniture,Bookcases
2,FUR-BO-10002613,"Atlantic Metals Mobile 4-Shelf Bookcases, Cust...",Furniture,Bookcases
3,FUR-BO-10001811,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",Furniture,Bookcases
4,FUR-BO-10004467,Bestar Classic Bookcase,Furniture,Bookcases
5,FUR-BO-10004015,"Bush Andora Bookcase, Maple/Graphite Gray Finish",Furniture,Bookcases
6,FUR-BO-10000112,"Bush Birmingham Collection Bookcase, Dark Cherry",Furniture,Bookcases
7,FUR-BO-10003660,"Bush Cubix Collection Bookcases, Fully Assembled",Furniture,Bookcases
8,FUR-BO-10004218,Bush Heritage Pine Collection 5-Shelf Bookcase...,Furniture,Bookcases
9,FUR-BO-10002824,Bush Mission Pointe Library,Furniture,Bookcases

In [17]:
dim_product.groupby("product_id").size().sort_values(ascending=False).head(10)

product_id
OFF-AR-10001149    2
FUR-FU-10001473    2
FUR-FU-10004017    2
OFF-BI-10004632    2
FUR-FU-10004270    2
FUR-CH-10001146    2
FUR-FU-10004848    2
FUR-FU-10004864    2
OFF-AP-10000576    2
FUR-FU-10004091    2
dtype: int64

In [18]:
dim_product[dim_product.duplicated(subset=["product_id"], keep=False)] \
    .sort_values("product_id")

,product_id,product_name,category,sub_category
16,FUR-BO-10002213,DMI Eclipse Executive Suite Bookcases,Furniture,Bookcases
47,FUR-BO-10002213,"Sauder Forest Hills Library, Woodland Oak Finish",Furniture,Bookcases
84,FUR-CH-10001146,"Global Task Chair, Black",Furniture,Chairs
86,FUR-CH-10001146,"Global Value Mid-Back Manager's Chair, Gray",Furniture,Chairs
175,FUR-FU-10001473,DAX Wood Document Frame,Furniture,Furnishings
...,...,...,...,...
1718,TEC-PH-10002200,Aastra 6757i CT Wireless VoIP phone,Technology,Phones
1821,TEC-PH-10002310,Panasonic KX T7731-B Digital phone,Technology,Phones
1833,TEC-PH-10002310,Plantronics Calisto P620-M USB Wireless Speake...,Technology,Phones
1815,TEC-PH-10004531,OtterBox Commuter Series Case - iPhone 5 & 5s,Technology,Phones
1711,TEC-PH-10004531,AT&T CL2909,Technology,Phones

In [19]:
dim_product = (
    df[["product_id", "product_name", "category", "sub_category"]]
    .drop_duplicates()
    .sort_values("product_id")
)

# Keep first occurrence per product_id
dim_product = dim_product.drop_duplicates(subset=["product_id"], keep="first")

In [20]:
print("Rows:", len(dim_product))
print("Unique product_id:", dim_product["product_id"].nunique())

Rows: 1862
Unique product_id: 1862