# 03 Build dim_customer

This notebook creates the customer dimension table from the cleaned sales dataset.

Each row in `dim_customer` represents one unique customer.

In [1]:
import pandas as pd
import os

In [2]:
input_path = "../data/processed/clean_sales.csv"
output_path = "../data/processed/dim_customer.csv"

In [3]:
df = pd.read_csv(input_path)
df.head()

,ï»¿row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,order_year,order_month,order_day,order_month_name,order_day_name,date_id
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,11,8,November,Tuesday,2016-11-08
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,11,8,November,Tuesday,2016-11-08
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,6,12,June,Sunday,2016-06-12
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,10,11,October,Sunday,2015-10-11
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,10,11,October,Sunday,2015-10-11

In [4]:
df[["customer_id", "customer_name", "segment"]].head()

  customer_id    customer_name    segment
0    CG-12520      Claire Gute   Consumer
1    CG-12520      Claire Gute   Consumer
2    DV-13045  Darrin Van Huff  Corporate
3    SO-20335   Sean O'Donnell   Consumer
4    SO-20335   Sean O'Donnell   Consumer

In [5]:
dim_customer = df[["customer_id", "customer_name", "segment"]].copy()
dim_customer = dim_customer.drop_duplicates()

In [6]:
print("Rows:", len(dim_customer))
print("Unique customer_id:", dim_customer["customer_id"].nunique())
print("Unique customer_name:", dim_customer["customer_name"].nunique())

Rows: 793
Unique customer_id: 793
Unique customer_name: 793

In [7]:
dim_customer[dim_customer.duplicated(subset=["customer_id"], keep=False)] \
    .sort_values("customer_id")

Empty DataFrame
Columns: [customer_id, customer_name, segment]
Index: []

In [8]:
dim_customer = (
    dim_customer
    .sort_values("customer_id")
    .drop_duplicates(subset=["customer_id"], keep="first")
    .reset_index(drop=True)
)

In [9]:
text_cols = ["customer_id", "customer_name", "segment"]

for col in text_cols:
    dim_customer[col] = dim_customer[col].astype(str).str.strip()

In [10]:
print("Rows:", len(dim_customer))
print("Unique customer_id:", dim_customer["customer_id"].nunique())
print("Unique customer_name:", dim_customer["customer_name"].nunique())
print("Segments:", dim_customer["segment"].unique())

Rows: 793
Unique customer_id: 793
Unique customer_name: 793
Segments: ['Consumer' 'Home Office' 'Corporate']

In [11]:
os.makedirs("../data/processed", exist_ok=True)

dim_customer.to_csv(output_path, index=False)

print(f"dim_customer saved to: {output_path}")

dim_customer saved to: ../data/processed/dim_customer.csv

In [12]:
dim_customer.head(10)

  customer_id         customer_name      segment
0    AA-10315            Alex Avila     Consumer
1    AA-10375          Allen Armold     Consumer
2    AA-10480          Andrew Allen     Consumer
3    AA-10645         Anna Andreadi     Consumer
4    AB-10015         Aaron Bergman     Consumer
5    AB-10060       Adam Bellavance  Home Office
6    AB-10105         Adrian Barton     Consumer
7    AB-10150           Aimee Bixby     Consumer
8    AB-10165           Alan Barnes     Consumer
9    AB-10255  Alejandro Ballentine  Home Office